apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHdwNWdnZi5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkRwQmJuVXhPVGs0STBBPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
